---
stages:
  - scan
  - build
  - deployment

scan_vulnerabilities_async_worker:
  stage: scan
  image: snyk/snyk-cli:python-3
  script:
    - cd ./async_worker
    - snyk test
  only:
    refs:
      - main
      - develop
    changes:
      - async_worker/**/*
      - .gitlab-ci.yml


build_and_push_to_repositories_async_worker:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    REPO_NAME: robarros
    IMAGE_NAME: async_worker
  script:
    - TAG=$(git describe --tags --abbrev=0)
    - cd ./async_worker
    - echo "{\"auths\":{\"https://index.docker.io/v1\":{\"auth\":\"$REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context . --dockerfile ./Dockerfile --destination $REPO_NAME/$IMAGE_NAME:$TAG
  only:
    refs:
      - main
      - develop
    changes:
      - async_worker/**/*
      - .gitlab-ci.yml

deploy_to_development_environment_async_worker:
  stage: deployment
  image: alpine/k8s:1.21.2
  environment:
    name: development
    url: https://dev.164.90.252.29.nip.io
  variables:
    REPO_NAME: robarros
    IMAGE_NAME: async_worker
    DEPLOY_NAME: async_worker
  script:
    - TAG=$(git describe --tags --abbrev=0)
    - mkdir /root/.kube
    - echo "${KUBECONFIG}" | base64 -d | tee > /root/.kube/config
    - cd ./async_worker/chart
    - sed -i "s|TAG|${TAG}|g" ./Chart.yaml
    - sed -i "s|TAG|${TAG}|g" ./values.yaml
    - sed -i "s|REPO_NAME|${REPO_NAME}/${IMAGE_NAME}|g" ./values.yaml
    - helm upgrade --install -n async_worker_dev $DEPLOY_NAME . -f values.yaml --create-namespace        
  only:
    refs:
      - develop
    changes:
      - async_worker/**/*
      - .gitlab-ci.yml

deploy_to_production_environment_async_worker:
  stage: deployment
  image: alpine/k8s:1.21.2
  environment:
    name: production
    url: "https://prod.164.90.252.29.nip.io"
  variables:
    REPO_NAME: robarros
    IMAGE_NAME: async_worker
    DEPLOY_NAME: async_worker
  script:
    - TAG=$(git describe --tags --abbrev=0)
    - mkdir /root/.kube
    - echo "${KUBECONFIG}" | base64 -d | tee > /root/.kube/config
    - cd ./async_worker/chart
    - sed -i "s|TAG|${TAG}|g" ./Chart.yaml
    - sed -i "s|TAG|${TAG}|g" ./values.yaml
    - sed -i "s|REPO_NAME|${REPO_NAME}/${IMAGE_NAME}|g" ./values.yaml
    - helm upgrade --install -n async_worker_prod $DEPLOY_NAME . -f values.yaml --create-namespace    
  when: manual
  only:
    refs:
      - main
    changes:
      - async_worker/**/*
      - .gitlab-ci.yml

