---
stages:
  - scan
  - build
  - deployment

scan_vulnerabilities_api_rest:
  stage: scan
  image: node:latest
  script:
    - npm install -g npm@latest
    - npm install -g snyk
    - cd ./api_rest
    - snyk auth
    - snyk test --file=app.py
  only:
    refs:
      - main
      - develop
    changes:
      - api_rest/**/*
      - .gitlab-ci.yml


build_and_push_to_repositories_api_rest:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    REPO_NAME: robarros
    IMAGE_NAME: api_rest
  script:
    - TAG=$(git describe --tags --abbrev=0)
    - cd ./api_rest
    - echo "{\"auths\":{\"https://index.docker.io/v1\":{\"auth\":\"$REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context . --dockerfile ./Dockerfile --destination $REPO_NAME/$IMAGE_NAME:$TAG
  only:
    refs:
      - main
      - develop
    changes:
      - api_rest/**/*
      - .gitlab-ci.yml

deploy_to_development_environment_api_rest:
  stage: deployment
  image: alpine/k8s:1.21.2
  environment:
    name: development
    url: https://dev.164.90.252.29.nip.io
  variables:
    REPO_NAME: robarros
    IMAGE_NAME: api_rest
    DEPLOY_NAME: api_rest
  script:
    - TAG=$(git describe --tags --abbrev=0)
    - mkdir /root/.kube
    - echo "${KUBECONFIG}" | base64 -d | tee > /root/.kube/config
    - cd ./api_rest/chart
    - sed -i "s|TAG|${TAG}|g" ./Chart.yaml
    - sed -i "s|TAG|${TAG}|g" ./values.yaml
    - sed -i "s|REPO_NAME|${REPO_NAME}/${IMAGE_NAME}|g" ./values.yaml
    - helm upgrade --install -n api_rest_dev $DEPLOY_NAME . -f values.yaml --create-namespace        
  only:
    refs:
      - develop
    changes:
      - api_rest/**/*
      - .gitlab-ci.yml

deploy_to_production_environment_api_rest:
  stage: deployment
  image: alpine/k8s:1.21.2
  environment:
    name: production
    url: "https://prod.164.90.252.29.nip.io"
  variables:
    REPO_NAME: robarros
    IMAGE_NAME: api_rest
    DEPLOY_NAME: api_rest
  script:
    - TAG=$(git describe --tags --abbrev=0)
    - mkdir /root/.kube
    - echo "${KUBECONFIG}" | base64 -d | tee > /root/.kube/config
    - cd ./api_rest/chart
    - sed -i "s|TAG|${TAG}|g" ./Chart.yaml
    - sed -i "s|TAG|${TAG}|g" ./values.yaml
    - sed -i "s|REPO_NAME|${REPO_NAME}/${IMAGE_NAME}|g" ./values.yaml
    - helm upgrade --install -n api_rest_prod $DEPLOY_NAME . -f values.yaml --create-namespace    
  when: manual
  only:
    refs:
      - main
    changes:
      - api_rest/**/*
      - .gitlab-ci.yml

